// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNaVlqFbTn22FxXAqqEHeQ85zjxGO36kc',
    appId: '1:184082808045:web:011ae96939c92e0c31e0e4',
    messagingSenderId: '184082808045',
    projectId: 'note-taking-app-dd450',
    authDomain: 'note-taking-app-dd450.firebaseapp.com',
    storageBucket: 'note-taking-app-dd450.appspot.com',
    measurementId: 'G-796XV02JVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwiyHk6Tuba_G8aLTmYGVW9VVaDaCeH9k',
    appId: '1:184082808045:android:bf09fc1d37dbf99a31e0e4',
    messagingSenderId: '184082808045',
    projectId: 'note-taking-app-dd450',
    storageBucket: 'note-taking-app-dd450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOA7RAm0DGlCknZU9TCCSVjueGqIyToN8',
    appId: '1:184082808045:ios:284f56aa26b078fd31e0e4',
    messagingSenderId: '184082808045',
    projectId: 'note-taking-app-dd450',
    storageBucket: 'note-taking-app-dd450.appspot.com',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOA7RAm0DGlCknZU9TCCSVjueGqIyToN8',
    appId: '1:184082808045:ios:284f56aa26b078fd31e0e4',
    messagingSenderId: '184082808045',
    projectId: 'note-taking-app-dd450',
    storageBucket: 'note-taking-app-dd450.appspot.com',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNaVlqFbTn22FxXAqqEHeQ85zjxGO36kc',
    appId: '1:184082808045:web:ef7dc50f571dc84531e0e4',
    messagingSenderId: '184082808045',
    projectId: 'note-taking-app-dd450',
    authDomain: 'note-taking-app-dd450.firebaseapp.com',
    storageBucket: 'note-taking-app-dd450.appspot.com',
    measurementId: 'G-H63F5SL295',
  );
}
